linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
#    - maligned
#    - lll
#    - dupl
#    - gocritic
#    - gochecknoinits
#    - gochecknoglobals

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 50