FROM golang:alpine as builder

RUN apk update && apk add --no-cache git

RUN go get github.com/pions/turn
RUN go install github.com/pions/turn/cmd/simple-turn

RUN adduser -D -g '' pion

FROM alpine:latest

COPY --from=builder /etc/passwd /etc/passwd
COPY --from=builder /go/bin/simple-turn /turn

USER pion

ENTRYPOINT ["/turn"]

# docker build -t turn -f Dockerfile.production .
# docker run -e REALM="localhost" -e USERS="username=password" -e UDP_PORT="3478" -p 3478:3478 turn